species_list = ['ailuropoda_melanoleuca', 'anas_platyrhynchos', 'anas_platyrhynchos_platyrhynchos', 'anser_cygnoides', 'aotus_nancymaae', 'astatotilapia_calliptera', 'astyanax_mexicanus', 
                'balaenoptera_musculus', 'betta_splendens', 'bison_bison_bison', 'bos_grunniens', 'bos_taurus', 'caenorhabditis_elegans', 'callorhinchus_milii', 'canis_lupus_dingo', 'canis_lupus_familiaris', 
                'carassius_auratus', 'cavia_porcellus', 'cebus_imitator', 'chelydra_serpentina', 'choloepus_hoffmanni', 'cricetulus_griseus_picr', 'danio_rerio', 'delphinapterus_leucas', 
                'dromaius_novaehollandiae', 'drosophila_melanogaster', 'equus_asinus', 'equus_caballus', 'felis_catus', 'gallus_gallus_gca000002315v5', 'gorilla_gorilla', 'homo_sapiens', 
                'loxodonta_africana', 'macaca_fascicularis', 'macaca_mulatta', 'malurus_cyaneus_samueli', 'maylandia_zebra', 'microtus_ochrogaster', 'mus_musculus', 'mus_musculus_129s1svimj', 
                'mus_musculus_aj', 'mus_musculus_akrj', 'mus_musculus_balbcj', 'mus_musculus_c3hhej', 'mus_musculus_c57bl6nj', 'mus_musculus_casteij', 'mus_musculus_cbaj', 'mus_musculus_dba2j', 
                'mus_musculus_fvbnj', 'mus_musculus_lpj', 'mus_musculus_nodshiltj', 'mus_musculus_nzohlltj', 'mus_musculus_pwkphj', 'mus_musculus_wsbeij', 'mus_spretus', 'mustela_putorius_furo', 
                'myotis_lucifugus', 'ornithorhynchus_anatinus', 'oryctolagus_cuniculus', 'ovis_aries', 'pan_paniscus', 'pan_troglodytes', 'panthera_leo', 'parus_major', 'phasianus_colchicus', 
                'physeter_catodon', 'prolemur_simus', 'rattus_norvegicus', 'rattus_norvegicus_shrspbbbutx', 'rattus_norvegicus_shrutx', 'rattus_norvegicus_wkybbb', 'rhinolophus_ferrumequinum', 
                'saccharomyces_cerevisiae', 'sarcophilus_harrisii', 'sciurus_vulgaris', 'sorex_araneus', 'suricata_suricatta', 'sus_scrofa', 'sus_scrofa_bamei', 'sus_scrofa_hampshire', 
                'tursiops_truncatus', 'ursus_americanus', 'vicugna_pacos', 'vombatus_ursinus', 'vulpes_vulpes']
